repo:
  users_base_path: "./db/users"
  urls_base_path: "./db/urls"
  sales_base_path: "./db/sales"

promo:
  gift: "Pa6JLqcTizErWYFM"
  start: "free:"
  count_req_friend: 5
  count_req_author: 3

tesseract:
  nlp_languages: ["rus", "eng"]

chat_gpt:
  content_start: ""

payment:
  message: "Количество месяцев: %d, цена: %dр"

  url:
    scheme: "https"
    host: "yoomoney.ru"
    path: "/quickpay/confirm.xml"

bot:
  port: 443
  url: "https://t.me/GPTutorBot"

  cert_path: "./certs/cert.crt"
  key_path: "./certs/cert.key"

  start_balance: 7

  admins_id: [261820904, 5128641039]

  shop:
    product_price_01: 295
    product_price_02: 749
    product_price_03: 1190
    product_sales_price_01: 99
    product_sales_price_02: 249
    product_sales_price_03: 399
    product_base_price_01: 295
    product_base_price_02: 749
    product_base_price_03: 1190
    product_count_01: 1
    product_count_02: 3
    product_count_03: 6

  messages:
    response:
      start: |
        Привет! 👋
        
        *GPTutor* 🧑‍🏫 — это сервис, который поможет тебе решить любое задание по учёбе, даже если у тебя есть только фотография условия задачи.

        🤖 *Бот умеет:*
        1. Создавать тексты для докладов, рефератов, презентаций со 100% оригинальностью
        2. Решать любые задачки
        3. Писать и редактировать программный код
        4. Переводить тексты с любого языка
        5. Читать текст с картинок
        6. Отвечать на вопросы и проходить тесты
        
        ⚙️ *Как начать?*
        - Если у тебя нет текста условия, но есть фото — пришли его сюда. GPTutor обработает фотографию 📷 и вернёт тебе текст.
        - Если условие у тебя есть — напиши сюда свой вопрос ✉️. Через некоторое время ChatGPT даст на него свой ответ.
        
        Остались вопросы? - пиши /help
        Не нашёл ответ? - обратись к разработчику @Emir\_Shimshir


      help: |
        *GPTutor* 🧑‍🏫 — это сервис, который поможет тебе решить любое задание по учёбе, даже если у тебя есть только фотография условия задачи.

        🤖 *Бот умеет:*
        1. Создавать тексты для докладов, рефератов, презентаций со 100% оригинальностью
        2. Решать любые задачки
        3. Писать и редактировать программный код
        4. Переводить тексты с любого языка
        5. Читать текст с картинок
        6. Отвечать на вопросы и проходить тесты
        
        ⚙️ *Как начать?*
        - Если у тебя нет текста условия, но есть фото — пришли его сюда. GPTutor обработает фотографию 📷 и вернёт тебе текст.
        - Если условие у тебя есть — напиши сюда свой вопрос ✉️. Через некоторое время ChatGPT даст на него свой ответ.
        
        Остались вопросы? - обратись к разработчику @Emir\_Shimshir

      balance: "Количество доступных запросов: "
      subscribe: "Подписка активна до: "

      buy_requests: |
        Чтобы пользоваться *GPTutor* без задержек и ограничений — оформи подписку 💎
        
        После оплаты проверь свой баланс.
        
        Остались вопросы? - обратись к разработчику @Emir\_Shimshir

      buy_requests_sales: |
        Чтобы пользоваться *GPTutor* без задержек и ограничений — оформи подписку 💎
        
        *АКЦИЯ!* Скидка *70%%* все виды подписок!
        
        _Подписок по специальной цене осталось:_ *%d*

        После оплаты проверь свой баланс.

        Остались вопросы? - обратись к разработчику @Emir\_Shimshir
      image: |
        Отправь изображение картинкой или файлом
      task: |
        Отправь текстом условие задачи
      got_text: |
        Задача обрабатывается...
      got_image: |
        Изображение обрабатывается...
      admin: |
        Доступные команды:
        
        /logs
        
        /dbUsers
        /dbUrls
        
        /createUser Name;ChatId;Balance;Day.Month.Year;UsedPromo
        /createUrl Utm;countRequests
        
        /deleteUser ChatID
        /deleteUrl Utm
        
        /sendAll message [*blod*] [_italics_] [[text](url)] [~snake~]
        
        /setSales count
        /getSales
        

      admin_db_users: "Формат вывода - Name;ChatId;Balance;day.month.year;UsedPromo\n\n"

      admin_db_urls: "Формат вывода - utm;count -> fullUrl\n\n"

      advice_button: |
        Изучи советы по работе с *GPTutor*, чтобы бот лучше помог решить твою задачу.
      advice_start: |
        *Советы:*

      advice01: |
        - Чтобы бот смог правильно выполнить задачу, добавь контекст и конкретные детали. Если у тебя есть какие-то особые требования или пожелания, не забудь об этом упомянуть.

      advice02: |
        - Не пиши бессмыслицу, не проси помощи у бота в чём-то незаконном (пиратство тоже считается)

      advice03: |
        - Если тебе нужно напечатать текст с картинки, то отправь боту обрезанное фото без лишних деталей.

      advice04: |
        - Ограничивай длину своих сообщений. Не стоит отправлять несколько страниц текста. Лучше напиши коротко и ясно, что тебе нужно. Иначе, есть вероятность, что тебе вернётся неполный ответ — GPTutor не может ответить тебе больше, чем на 4000 символов.

      promo: |
        Отправь текстом промокод друга, чтобы получить бесплатные запросы

      Promo_ok: |
        Промокод успешно активирован

      create_promo01: |
        Твой уникальный промокод, за каждого приведенного друга ты получишь 3 бесплатных запроса:

      create_promo02: |
        Отправь сообщение другу:

      create_promo03: |
        *GPTutor* 🧑‍🏫 — это сервис, который поможет тебе решить любое задание по учёбе, даже если у тебя есть только фотография условия задачи.

        🤖 *Бот умеет:*
        1. Создавать тексты для докладов, рефератов, презентаций со 100%% оригинальностью
        2. Решать любые задачки
        3. Писать и редактировать программный код
        4. Переводить тексты с любого языка
        5. Читать текст с картинок
        6. Отвечать на вопросы и проходить тесты
        
        Введи мой промокод: 
        
        *%s*
        
        Получи 5 дополнительных запросов
        
        Пользуйся [@GPTutor](https://t.me/GPTutorBot?start=promo) уже сейчас!

    error:
      unknown_message: |
        Я не понимаю твоё сообщение 😢 
        Отправь текст или фото с условием задачи

      unknown_command: |
        Я не знаю такую команду 😡
        При возникновении вопросов введи команду /help

      unknown_callback: |
        Ошибка при нажатии кнопки

      not_auth: | 
        Ты не авторизован, введи команду: /start
      admin_error: |
        Ошибка доступа

      admin_usage_error: |
        Ошибка ввода команды

      default: |
        Произошла неизвестная ошибка 🤕

      promo_error: |
        Ошибка ввода промокода

      promo_used_error: |
        Промокод уже активирован

  keyboard:
    menu:
      help: "Помощь"
      balance: "Баланс"
      promo: "Промокод"
      image_recognize: "Распознать картинку"
      solve_task: "Решить задачу"
    balance:
      buy: "Оформить подписку"
    advices:
      advice: "Советы"
    promo:
      create_promo: "Создать свой промокод"

  commands:
    start: "start"
    help: "help"
    admin: "admin"
    logs: "logs"
    db_users: "dbUsers"
    db_urls: "dbUrls"
    create_user: "createUser"
    create_url: "createUrl"
    delete_user: "deleteUser"
    delete_url: "deleteUrl"
    send_all: "sendAll"
    set_sales: "setSales"
    get_sales: "getSales"

server:
  port: 80
